import logging
import random
import time
from typing import List, Optional

from .llm_client import LLMClient
from ..core.system_detector import SystemInfo
from ..core.security import SafetyCheck, SecurityViolation

# Retries per provider before trying the next fallback client.
_MAX_API_RETRIES = 3


def _is_retryable_api_error(exc: BaseException) -> bool:
    """True for transient provider errors where a short backoff may succeed."""
    msg = str(exc).lower()
    needles = (
        "429",
        "rate limit",
        "too many requests",
        "resource exhausted",
        "503",
        "502",
        "504",
        "timeout",
        "timed out",
        "temporarily unavailable",
        "overloaded",
        "connection reset",
        "connection refused",
        "eof occurred",
    )
    if any(n in msg for n in needles):
        return True
    name = type(exc).__name__.lower()
    return any(
        frag in name
        for frag in (
            "ratelimit",
            "timeout",
            "serviceunavailable",
            "apierror",
            "internalserver",
        )
    )


class CommandGenerator:
    def __init__(
        self,
        llm_client: LLMClient,
        system_info: SystemInfo,
        fallback_clients: Optional[List[LLMClient]] = None,
    ):
        self.llm = llm_client
        self.system_info = system_info
        self._clients: List[LLMClient] = [llm_client]
        if fallback_clients:
            for c in fallback_clients:
                if c is not None and c not in self._clients:
                    self._clients.append(c)

    def generate_command(self, user_request: str) -> str:
        """
        Converts a natural language request into a shell command.
        Validates the generated command through SafetyCheck before returning.
        Retries transient API failures on the same client, then tries fallback
        clients (same spirit as the planner).
        """
        prompt = self._build_prompt(user_request)
        last_error: Optional[Exception] = None

        for client_idx, client in enumerate(self._clients):
            if client_idx > 0:
                delay = min(1.0 + random.random(), 3.0)
                time.sleep(delay)
            client_name = type(client).__name__
            client_last_error: Optional[Exception] = None

            for api_try in range(_MAX_API_RETRIES):
                if api_try > 0:
                    backoff = min(2.0**api_try, 12.0) + random.random()
                    time.sleep(backoff)
                try:
                    response_text = client.generate_response(prompt)
                    command = self._parse_response(response_text).strip()
                    if not command:
                        client_last_error = RuntimeError(
                            "LLM returned an empty command"
                        )
                        if api_try + 1 < _MAX_API_RETRIES:
                            logging.warning(
                                f"[CommandGenerator] {client_name}: empty response, retrying"
                            )
                            continue
                        logging.warning(
                            f"[CommandGenerator] {client_name}: empty after "
                            f"{_MAX_API_RETRIES} tries, next client"
                        )
                        break

                    try:
                        SafetyCheck.check_command(command)
                    except SecurityViolation as e:
                        raise SecurityViolation(
                            f"LLM generated an unsafe command: {e}. "
                            f"Original request: '{user_request}'"
                        )

                    # Record on the client that actually produced the command (fallbacks may
                    # use a different memory backend than the primary).
                    mem = getattr(client, "memory_client", None)
                    if mem:
                        mem.add_memory(
                            content=(
                                f"User requested: '{user_request}'. "
                                f"Nexus generated: '{command}'"
                            ),
                            metadata={
                                "type": "command_generation",
                                "os": self.system_info.os_name,
                            },
                        )

                    if client_idx > 0 or api_try > 0:
                        logging.info(
                            f"Command generated by {client_name}"
                            + (
                                f" (fallback client, attempt {client_idx})"
                                if client_idx > 0
                                else f" (retry {api_try})"
                            )
                        )
                    return command

                except SecurityViolation:
                    raise
                except Exception as e:
                    client_last_error = e
                    if api_try + 1 < _MAX_API_RETRIES and _is_retryable_api_error(e):
                        logging.warning(
                            f"[CommandGenerator] {client_name} API error "
                            f"(retry {api_try + 1}/{_MAX_API_RETRIES}): {e}"
                        )
                        continue
                    logging.warning(f"[CommandGenerator] {client_name} failed: {e}")
                    break

            last_error = client_last_error or last_error

        if last_error is not None:
            raise last_error
        raise RuntimeError("Command generation failed: no LLM clients configured")

    def _build_prompt(self, request: str) -> str:
        # --- RAG: Retrieve Proven Solutions ---
        memory_context = ""
        if self.llm.memory_client:
            # tailored query
            rag_hits = self.llm.memory_client.query_memory(
                f"feedback {request}", limit=3
            )
            if rag_hits:
                memory_context = f"\n### PROVEN SOLUTIONS (FROM MEMORY)\n{rag_hits}\n"

        return f"""
You are Nexus, an elite intelligent Linux Assistant.
Your purpose is to autonomously design and generate safe, efficient, and robust CLI solutions.

### SYSTEM CONTEXT
- OS: {self.system_info.os_name} {self.system_info.os_version}
- Package Manager: {self.system_info.package_manager.value}

### INTELLIGENCE CORE & MEMORY
You have access to a persistent memory stream.{memory_context}
1. **Context Absorption**: Read the "PROVEN SOLUTIONS" provided above carefully.
2. **Preference Recognition**: Identify user habits (e.g., "user likes podman over docker", "user uses zsh").
3. **Continuous Improvement**: If the context shows a past failure for a similar task, ADAPT your strategy. Do not repeat mistakes. Use SUCCESSFUL commands as a template.

### DESIGN PHILOSOPHY
1. **Idempotency**: Where possible, generate commands that can be run multiple times safely.
2. **Modularity**: Chain small tools (`grep`, `awk`, `xargs`) rather than complex custom logic.
3. **Safety**: NEVER run destructive commands (`rm -rf /`) without safeguards or explicit user intent.
4. **Efficiency**: Use the most modern tools available on the system.

### OUTPUT RULES
- Return **ONLY** the executable CLI command string.
- NO markdown code blocks (```).
- NO introductory text or explanations.
- If multiple steps are required, join them logically with `&&` or `;`.

### USER REQUEST
"{request}"

### GENERATED SOLUTION
"""

    def _parse_response(self, response: str) -> str:
        # Cleanup any markdown or extra whitespace
        cleaned = response.strip()
        if cleaned.startswith("```"):
            cleaned = cleaned.split("\n", 1)[1]
        if cleaned.endswith("```"):
            cleaned = cleaned.rsplit("\n", 1)[0]
        cleaned = cleaned.replace("`", "")  # Remove inline code ticks if any
        return cleaned.strip()
