"""
Command Validator - Validates generated commands before execution.

This module provides safety checks and validation for commands
generated by the LLM to ensure they are safe and syntactically correct.
Includes FTP-related checks (credentials on the command line, anonymous FTP).
"""

import re
import shlex
from pathlib import Path
from typing import Tuple, Optional, List, Union
from dataclasses import dataclass


class SecurityViolation(Exception):
    pass


@dataclass
class ValidationResult:
    """Result of command validation."""

    is_valid: bool
    reasoning: str
    sanitized_command: Optional[str] = None
    warnings: Optional[List[str]] = None

    def __post_init__(self):
        if self.warnings is None:
            self.warnings = []


class CommandValidator:
    """
    Validates commands before execution.

    Checks for:
    - Syntax errors
    - Dangerous patterns
    - Invalid shell constructs
    - Proper escaping
    """

    # Dangerous patterns that should trigger warnings
    # NOTE: "rm -rf /" must match ONLY true root deletes, not /tmp, /usr, /var, ...
    # Lookahead must NOT use \s — that includes \n/\r and false-positives on
    # "rm -rf /\n/tmp/foo" (newline between / and tmp looks like "then whitespace after /").
    # Only allow: end, ;, &&, ||, or spaces/tabs then those (horizontal whitespace only).
    _RM_RF_ROOT_LOOKAHEAD = r"(?=$|;|&&|\|\||[ \t]+(?:$|;|&&|\|\|))"
    # FTP Security — risk-based execution model.
    # Cleartext on the wire is implied — prefer HTTPS/SFTP where possible.
    #
    # Risk tiers:
    #   CRITICAL (BLOCKED)  — always rejected, broken by design
    #     echo "pass" | ftp, heredoc ftp — hangs in subprocess, leaks credentials
    #   HIGH (DANGEROUS)    — blocked in auto-execution, requires user confirmation
    #     ftp://user:pass@host, --ftp-password=X, lftp -u user,pass — credential exposure
    #   LOW                 — safe, auto-execute
    #     lftp host, ftp host (no credentials in command)
    _FTP_BLOCKED_PATTERNS = [
        # Piping password to ftp via echo — visible in process list, hangs in subprocess
        (
            r"(?i)echo\s+.*\|\s*ftp\b",
            "Piping password to ftp via echo (insecure and hangs in non-interactive mode); "
            "use interactive lftp instead",
        ),
        # Heredoc with basic ftp — hangs in subprocess capture mode
        (
            r"(?i)\bftp\b[^\n]*<<",
            "ftp with heredoc hangs in non-interactive mode; "
            "use interactive lftp instead",
        ),
        # lftp -e with 'user' login command — credentials embedded in command string,
        # visible in ps aux, shell history, and logs
        (
            r"(?i)lftp\s+.*?-e\s+['\"].*\buser\s+\S+\s+\S+",
            "lftp -e 'user name password' embeds credentials in the command string "
            "(visible in ps aux, shell history, logs); use interactive lftp instead",
        ),
        # lftp -e with destructive FTP operations — must be isolated and confirmed
        (
            r"(?i)lftp\s+.*?-e\s+['\"].*\b(mdelete|mrm|rm\s|rmdir|glob\s+rm)\b",
            "lftp -e contains destructive FTP operation (mdelete/mrm/rm); "
            "destructive actions must not be combined with connection — "
            "use interactive lftp and confirm deletions separately",
        ),
    ]
    _FTP_DANGEROUS_PATTERNS = [
        # user:password@host inside ftp:// (and quoted variants)
        (
            r"(?i)ftp://[^\s/'\"]+:[^\s/'\"@]+@",
            "FTP URL embeds a password (visible in shell history and process list); "
            "use interactive lftp without inline credentials",
        ),
        (
            r"(?i)--ftp-password=[^\s]+",
            "FTP password on the command line (--ftp-password); use a .netrc file or SFTP/SSH",
        ),
        # lftp -u user,pass — credentials visible in ps aux, shell history, and logs
        (
            r"(?i)lftp\s+.*?-u\s+[^,\s]+,\S+",
            "lftp -u user,password exposes credentials on the command line "
            "(visible in ps aux, shell history, logs); use interactive lftp or ~/.netrc",
        ),
        (
            r"(?i)(curl|wget|ftp|ftpget)\s+[^\n;]*?("
            r"-u\s+anonymous\b|--ftp-user[= ]anonymous\b|"
            r"ftp://anonymous@|ftp://anonymous:)",
            "Anonymous FTP login (legacy risk; prefer authenticated HTTPS or SFTP)",
        ),
    ]
    DANGEROUS_PATTERNS = [
        (
            r"rm\s+-[a-zA-Z]*r[a-zA-Z]*\s+/" + _RM_RF_ROOT_LOOKAHEAD,
            "Recursive delete on root directory",
        ),
        (r"rm\s+-[a-zA-Z]*r[a-zA-Z]*\s+/\*", "Recursive delete on root wildcard"),
        (r"dd\s+if=/dev/(zero|urandom)\s+of=/dev/sd", "Disk wipe operation"),
        (r":\(\)\s*\{.*:\s*\|\s*:.*\}\s*;?\s*:", "Fork bomb pattern"),
        (r"mkfs\.", "Filesystem format operation"),
        (r"chmod\s+-R\s+777", "Overly permissive recursive chmod"),
        (r"wget.*\|\s*bash", "Piping download directly to bash"),
        (r"curl.*\|\s*sh", "Piping download directly to shell"),
        (r"eval\s+\$\(", "Eval with command substitution"),
    ] + _FTP_DANGEROUS_PATTERNS

    # Patterns that are always blocked
    BLOCKED_PATTERNS = [
        (
            r"rm\s+-[a-zA-Z]*r[a-zA-Z]*\s+/" + _RM_RF_ROOT_LOOKAHEAD,
            "Attempting to delete root directory",
        ),
        (r"rm\s+-[a-zA-Z]*r[a-zA-Z]*\s+/\*", "Attempting to delete root wildcard"),
        (r":\(\)\s*\{.*:\s*\|\s*:.*\}\s*;?\s*:", "Fork bomb detected"),
    ] + _FTP_BLOCKED_PATTERNS

    def __init__(self):
        self.strict_mode = False

    def validate(self, command: str, strict: bool = False) -> ValidationResult:
        """
        Validate a command.

        Args:
            command: The command string to validate
            strict: If True, applies stricter validation rules

        Returns:
            ValidationResult with validation status
        """
        if not command or not command.strip():
            return ValidationResult(is_valid=False, reasoning="Empty command")

        command = command.strip()
        warnings = []

        # Check for blocked patterns
        for pattern, reason in self.BLOCKED_PATTERNS:
            if re.search(pattern, command, re.IGNORECASE):
                return ValidationResult(is_valid=False, reasoning=f"Blocked: {reason}")

        # Check for dangerous patterns
        for pattern, reason in self.DANGEROUS_PATTERNS:
            if re.search(pattern, command, re.IGNORECASE):
                warnings.append(f"Warning: {reason}")

        # Check syntax
        syntax_valid, syntax_msg = self._check_syntax(command)
        if not syntax_valid:
            return ValidationResult(
                is_valid=False, reasoning=f"Syntax error: {syntax_msg}"
            )

        # Check for suspicious characteristics
        suspicious = self._check_suspicious(command)
        warnings.extend(suspicious)

        # If strict mode and warnings exist, fail
        if strict and warnings:
            return ValidationResult(
                is_valid=False,
                reasoning=f"Strict mode: {', '.join(warnings)}",
                warnings=warnings,
            )

        return ValidationResult(
            is_valid=True,
            reasoning="Command validated successfully",
            sanitized_command=command,
            warnings=warnings,
        )

    def _check_syntax(self, command: str) -> Tuple[bool, str]:
        """
        Check basic shell syntax.

        Returns:
            (is_valid, error_message)
        """
        # Check for mismatched quotes
        single_quotes = command.count("'")
        double_quotes = command.count('"')

        if single_quotes % 2 != 0:
            return False, "Mismatched single quotes"
        if double_quotes % 2 != 0:
            return False, "Mismatched double quotes"

        # Check for unbalanced parentheses/braces
        if command.count("(") != command.count(")"):
            return False, "Unbalanced parentheses"
        if command.count("{") != command.count("}"):
            return False, "Unbalanced braces"
        if command.count("[") != command.count("]"):
            return False, "Unbalanced brackets"

        # Try to parse with shlex (basic check)
        try:
            # Only parse if no shell operators (which shlex can't handle)
            if not any(op in command for op in ["&&", "||", "|", ">", "<", ";"]):
                shlex.split(command)
        except ValueError as e:
            return False, f"Parse error: {str(e)}"

        return True, ""

    def _check_suspicious(self, command: str) -> List[str]:
        """
        Check for suspicious patterns that aren't necessarily blocked.

        Returns:
            List of warning messages
        """
        warnings = []

        # Check for command obfuscation
        if re.search(r"\$\{.*\}|\$\(.*\)", command):
            # Command substitution is common, only warn if nested or complex
            nesting_level = command.count("$(")
            if nesting_level > 2:
                warnings.append("Complex nested command substitution detected")

        # Check for base64 encoding (common in attacks)
        if "base64" in command.lower() and "|" in command:
            warnings.append("Base64 decode piped to execution")

        # Check for hex/octal encoding
        if re.search(r"\\x[0-9a-f]{2}|\\[0-7]{3}", command):
            warnings.append("Hex or octal encoding detected")

        # Check for multiple chained commands
        chain_count = command.count("&&") + command.count("||") + command.count(";")
        if chain_count > 5:
            warnings.append(f"Excessive command chaining ({chain_count} operators)")

        # Check for downloads to executable locations
        if any(pattern in command.lower() for pattern in ["wget", "curl"]) and any(
            loc in command for loc in ["/usr/bin", "/bin", "/sbin", "/usr/local/bin"]
        ):
            warnings.append("Download to system executable directory")

        return warnings

    def suggest_fix(self, command: str, error: str) -> Optional[str]:
        """
        Attempt to suggest a fix for an invalid command.

        Args:
            command: The invalid command
            error: The validation error message

        Returns:
            Suggested fixed command, or None if can't fix
        """
        if "Mismatched" in error and "quotes" in error:
            # Try to balance quotes
            if error.startswith("Mismatched single"):
                return command + "'"
            elif error.startswith("Mismatched double"):
                return command + '"'

        # More sophisticated fixes could be added here
        return None


validator = CommandValidator()


# ── Credential Scrubbing ─────────────────────────────────────────────────────
# Patterns that match credentials in user input / commands.
# Used to redact before logging, session storage, and memory/RAG.
_CREDENTIAL_PATTERNS = [
    # ftp://user:pass@host → ftp://***:***@host
    (re.compile(r"(ftp://)[^\s/'\"]+:[^\s/'\"@]+@"), r"\1***:***@"),
    # lftp -u user,pass → lftp -u ***,***
    (re.compile(r"(lftp\s+.*?-u\s+)\S+,\S+", re.IGNORECASE), r"\1***,***"),
    # 'user <name> <password>' inside lftp -e strings → 'user *** ***'
    (re.compile(r"(\buser\s+)\S+\s+\S+", re.IGNORECASE), r"\1*** ***"),
    # --ftp-password=X → --ftp-password=***
    (re.compile(r"(--ftp-password=)\S+", re.IGNORECASE), r"\1***"),
    # Generic user:pass@host patterns (ssh, etc.)
    (re.compile(r"(://)[^\s/'\"]+:[^\s/'\"@]+@"), r"\1***:***@"),
]


def scrub_credentials(text: str) -> str:
    """Redact credentials from a string for safe logging/storage.

    Handles ftp://user:pass@host, lftp -u user,pass, --ftp-password=X,
    and generic protocol://user:pass@host patterns.
    Returns a copy with credentials replaced by '***'.
    """
    result = text
    for pattern, replacement in _CREDENTIAL_PATTERNS:
        result = pattern.sub(replacement, result)
    return result


class SafetyCheck:
    @classmethod
    def is_path_within_any_root(
        cls, candidate: Union[str, Path], roots: List[Path]
    ) -> bool:
        """
        True if candidate resolves to a path inside one of the roots.

        Uses Path.relative_to (not str.startswith) so a prefix like
        /home/user does not incorrectly allow /home/user2/secret.
        """
        try:
            resolved = Path(candidate).expanduser().resolve()
        except (OSError, RuntimeError):
            return False
        for root in roots:
            try:
                base = root.expanduser().resolve()
                resolved.relative_to(base)
                return True
            except ValueError:
                continue
            except (OSError, RuntimeError):
                continue
        return False

    @classmethod
    def check_command(cls, command: str) -> bool:
        """
        Checks if a command is potentially destructive using the CommandValidator.
        Returns True if safe, raises SecurityViolation if unsafe.
        """
        result = validator.validate(command, strict=True)
        if not result.is_valid:
            raise SecurityViolation(
                f"Command blocked by safety filter: {result.reasoning}"
            )
        return True

    @classmethod
    def is_sudo_required(cls, command: str) -> bool:
        """
        Heuristic to check if a command likely needs sudo.
        """
        # NOTE: "chmod" is intentionally omitted. User-owned files (AppImage in ~/Downloads,
        # ~/.local/bin) must NOT go through interactive sudo — that path blocks the TUI on a
        # password prompt with no timeout. System paths still match " /etc/"|"/usr/"|"/var/" below.
        privileged_commands = [
            "apt",
            "dnf",
            "pacman",
            "systemctl",
            "mount",
            "umount",
            "chown",
        ]
        first_word = command.split()[0] if command else ""

        if first_word in privileged_commands:
            return True

        # Cloud CLIs manage their own authentication and MUST NOT be run with sudo,
        # otherwise they lose the local user's ~/.azure/ credential cache.
        if first_word in ["az", "aws", "gcloud"]:
            return False

        # Check for writes to system directories
        if " /etc/" in command or " /usr/" in command or " /var/" in command:
            return True

        return False
